name: Build Zalo for Linux

on:
  workflow_dispatch:
    inputs:
      dmg_url:
        description: 'Zalo DMG Download URL'
        required: true
        default: 'https://res-download-pc-te-vnso-pt-51.zadn.vn/mac/ZaloSetup-universal-25.5.3.dmg'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Cache Electron binaries
      uses: actions/cache@v3
      with:
        path: ~/.cache/electron
        key: ${{ runner.os }}-electron-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-electron-
          
    - name: Install system dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends p7zip-full
        
    - name: Install Node.js dependencies
      run: npm ci --prefer-offline --no-audit
      
    - name: Extract Zalo from DMG
      env:
        DMG_URL: ${{ github.event.inputs.dmg_url }}
      run: |
        echo "🚀 Starting extraction with DMG URL: $DMG_URL"
        npm run extract-dmg
        
    - name: Build AppImage
      id: build
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "🔨 Building Zalo AppImage..."
        npm run build
        
    - name: Upload AppImage artifact
      uses: actions/upload-artifact@v4
      with:
        name: zalo-linux-${{ steps.build.outputs.release_tag }}
        path: ${{ steps.build.outputs.appimage_file }}
        retention-days: 30
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.build.outputs.release_tag }}
        name: Zalo for Linux ${{ steps.build.outputs.release_tag }}
        body: |
          # Zalo for Linux ${{ steps.build.outputs.release_tag }}
          
          🎉 **Unofficial Zalo port for Linux systems**
          
          ## 📥 Download
          - **File**: `${{ steps.build.outputs.appimage_name }}`
          - **Size**: `${{ steps.build.outputs.file_size }}`
          - **Format**: AppImage (portable, no installation required)
          - **SHA256**: `${{ steps.build.outputs.file_sha256 }}`
          
          ## 🚀 How to use
          ```bash
          # Download and verify
          wget https://github.com/${{ github.repository }}/releases/download/${{ steps.build.outputs.release_tag }}/${{ steps.build.outputs.appimage_name }}
          echo "${{ steps.build.outputs.file_sha256 }}  ${{ steps.build.outputs.appimage_name }}" | sha256sum -c
          
          # Make executable and run
          chmod +x ${{ steps.build.outputs.appimage_name }}
          ./${{ steps.build.outputs.appimage_name }}
          ```
          
          ## ⚠️ Important Notes
          - This is an **unofficial** port from the macOS version
          - Version automatically synced from official Zalo macOS app: **${{ steps.build.outputs.release_tag }}**
          - Source DMG: `${{ github.event.inputs.dmg_url }}`
          
          ## 📋 System Requirements
          - Linux x64
          - GLIBC 2.28 or later
          - Desktop environment with system tray support (recommended)
          
          ## 🐛 Issues & Support
          Please report issues in the [GitHub Issues](https://github.com/${{ github.repository }}/issues) section.
          
          ---
          *Built automatically from macOS version using GitHub Actions*
        files: ${{ steps.build.outputs.appimage_file }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 